# Generated by Django 3.0.3 on 2020-02-16 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('sno', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('content', models.TextField()),
                ('auther', models.CharField(max_length=13)),
                ('timestamp', models.DateField(blank=True)),
            ],
        ),
    ]
