# Generated by Django 3.0.3 on 2020-02-17 17:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_post_slug'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='datetime',
            new_name='timestamp',
        ),
    ]
